name: study_app
description: StudyAI - AI-powered study companion
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
    

  # FCM — push notifications from backend
  firebase_messaging: ^15.1.0
  flutter_secure_storage: ^9.2.2
  device_info_plus: ^11.5.0
  connectivity_plus: ^6.1.5
  # Local notifications — show notification UI on device
  flutter_local_notifications: ^17.2.0
  timezone: ^0.9.4 
  

  # HTTP client — used by api_client.dart
  http: ^1.2.1
  google_sign_in: ^6.2.1
  
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0

  # Local storage — saves JWT token and user data
  shared_preferences: ^2.2.3

  # File picker — lets students upload PDFs
  file_picker: ^8.0.3

  # Image picker — for profile picture
  image_picker: ^1.1.2

  # Video player — for YouTube screen (or use webview)
  webview_flutter: ^4.7.0

  # URL launcher — open YouTube links in browser
  url_launcher: ^6.3.0

  # Cached network image — for thumbnails and profile pics
  cached_network_image: ^3.3.1

  # Loading animations
  shimmer: ^3.0.0
  lottie: ^3.1.2

  # Charts — for performance/ML analytics screen
  fl_chart: ^0.68.0

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # - assets/animations/
