// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhRYYkt2Ft1Y6Z_sNZWfqfijPeeP4tVaM',
    appId: '1:709449691227:android:7530f1460ce66f564ccf7e',
    messagingSenderId: '709449691227',
    projectId: 'calculator-ce8e9',
    storageBucket: 'calculator-ce8e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Nx_MYDLprhBvLKAViK6kXVdUsimD5tA',
    appId: '1:709449691227:ios:c9decc6eae3685c94ccf7e',
    messagingSenderId: '709449691227',
    projectId: 'calculator-ce8e9',
    storageBucket: 'calculator-ce8e9.firebasestorage.app',
    androidClientId: '709449691227-7shbvbcf9aii7239dfic4s18nh724fnb.apps.googleusercontent.com',
    iosClientId: '709449691227-q3786urm7nf77pb9b5fe6qgk5e26nirk.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiLearningApp',
  );
}
